# ==================================================
# Z-PAY HYBRID FRAUD DETECTION PIPELINE
# ==================================================
# This module detects suspicious financial transactions using a hybrid machine learning approach.
#
# Pipeline Overview:
# 1. Load processed transaction data
# 2. Feature engineering for fraud signals
# 3. Encode categorical variables
# 4. Detect anomalies using Isolation Forest
# 5. Generate pseudo fraud labels
# 6. Train Random Forest fraud classifier
# 7. Generate fraud risk scores
# 8. Produce fraud explanations
# 9. Save final fraud-analysis dataset
#
# This approach is useful when real fraud labels are not available in the dataset.
# ==================================================

import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import (
    IsolationForest,
    RandomForestClassifier
)

# ==================================================
# 1. LOAD PROCESSED TRANSACTION DATA
# ==================================================
# The fraud detection pipeline uses the processed dataset generated by the expense categorization model.

df = pd.read_csv("../data/processed/transactions_final.csv")

print("Total transactions loaded:", len(df))


# ==================================================
# 2. FEATURE ENGINEERING – TIME-BASED SIGNALS
# ==================================================
# Machine learning models cannot understand timestamps
# directly, so we extract behavioral signals such as:
#
# hour        -> time of transaction (0–23)
# day_of_week -> weekday pattern (0=Monday, 6=Sunday)
#
# These patterns often reveal abnormal behavior.

df["transaction_time"] = pd.to_datetime(
    df["transaction_time"],
    errors="coerce"
).dt.floor("s")

df["hour"] = df["transaction_time"].dt.hour
df["day_of_week"] = df["transaction_time"].dt.dayofweek

print("\nSample dataset with engineered time features:\n")
print(df.head().to_string())


# ==================================================
# 3. ENCODE CATEGORICAL FEATURES
# ==================================================
# Machine learning models require numerical inputs.
# Therefore, we convert categorical variables into numeric representations using LabelEncoder.
#
# Encoded columns:
# final_category -> category_encoded
# location       -> location_encoded
# device_id      -> device_encoded

category_encoder = LabelEncoder()
location_encoder = LabelEncoder()
device_encoder = LabelEncoder()

df["category_encoded"] = category_encoder.fit_transform(df["final_category"])
df["location_encoded"] = location_encoder.fit_transform(df["location"])
df["device_encoded"] = device_encoder.fit_transform(df["device_id"])


# ==================================================
# 4. SELECT FEATURES FOR FRAUD DETECTION
# ==================================================
# The fraud model learns behavioral patterns using:
#
# amount           -> transaction value
# hour             -> time of day
# day_of_week      -> weekday patterns
# category_encoded -> spending category
# location_encoded -> geographical signal
# device_encoded   -> device identity

fraud_features = df[[
    "amount",
    "hour",
    "day_of_week",
    "category_encoded",
    "location_encoded",
    "device_encoded"
]]

print("\nFraud feature matrix preview:\n")
print(fraud_features.head().to_string())


# ==================================================
# 5. ANOMALY DETECTION USING ISOLATION FOREST
# ==================================================
# Isolation Forest identifies unusual transactions by
# isolating data points that behave very differently
# from the majority of the dataset.
#
# contamination=0.05 means we assume roughly
# 5% of transactions may be suspicious.

iso_model = IsolationForest(
    n_estimators=100,
    contamination=0.05,
    random_state=42
)

# Train anomaly detector
iso_model.fit(fraud_features)

# Predict anomalies
iso_predictions = iso_model.predict(fraud_features)

# Convert anomaly output:
#  1  -> normal
# -1  -> anomaly
df["pseudo_fraud_label"] = iso_predictions
df["pseudo_fraud_label"] = df["pseudo_fraud_label"].map({1: 0, -1: 1})

print("\nSuspicious transactions detected (Isolation Forest):",
      df["pseudo_fraud_label"].sum())


# ==================================================
# 6. TRAIN RANDOM FOREST FRAUD CLASSIFIER
# ==================================================
# Isolation Forest detects unusual transactions but
# does not learn stable fraud patterns.
#
# Therefore, we use the anomalies detected by
# Isolation Forest as pseudo fraud labels and train
# a Random Forest classifier to learn consistent
# fraud behavior and generate fraud risk scores.
#
# This creates a hybrid system:
#   Isolation Forest → detect anomalies
#   Random Forest    → learn fraud patterns

# Model inputs
x_fraud = fraud_features

# Target labels
y_fraud = df["pseudo_fraud_label"]

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

# Train classifier
rf_model.fit(x_fraud, y_fraud)


# ==================================================
# 7. FRAUD RISK SCORING
# ==================================================
# Instead of binary classification, the model produces
# a fraud probability score between 0 and 1.

fraud_probabilities = rf_model.predict_proba(x_fraud)[:, 1]

df["risk_score"] = fraud_probabilities

# Apply threshold to flag high-risk transactions
df["is_fraud"] = df["risk_score"] > 0.7


# ==================================================
# 8. FRAUD DETECTION SUMMARY
# ==================================================

print("\nFraud detection summary:\n")

print("Total transactions:", len(df))
print("Pseudo fraud detected (Isolation Forest):",
      df["pseudo_fraud_label"].sum())

print("\nTransactions flagged by Random Forest:",
      df["is_fraud"].sum())

print("\nAverage fraud risk score:",
      df["risk_score"].mean())

print("\nTop risky transactions:\n")

print(
    df[["amount", "hour", "final_category", "risk_score", "is_fraud"]]
    .sort_values(by="risk_score", ascending=False)
    .head(10)
)


# ==================================================
# 9. FRAUD EXPLANATION ENGINE
# ==================================================
# This component provides interpretable explanations
# for flagged transactions. It helps analysts
# understand why a transaction was considered risky.

def explain_fraud(row):

    reasons = []

    if row["amount"] > 50000:
        reasons.append("High transaction amount")

    if row["hour"] <= 4:
        reasons.append("Late-night transaction")

    if row["device_encoded"] > df["device_encoded"].quantile(0.9):
        reasons.append("Rare device usage")

    if row["location_encoded"] > df["location_encoded"].quantile(0.9):
        reasons.append("Unusual location")

    if row["risk_score"] > 0.9:
        reasons.append("Very high fraud probability")

    return ", ".join(reasons)


df["fraud_reason"] = df.apply(explain_fraud, axis=1)

print("\nExample flagged transactions with explanations:\n")
print(
    df[df["is_fraud"] == True][[
        "transaction_id",
        "amount",
        "final_category",
        "transaction_time",
        "location",
        "device_id",
        "is_fraud",
        "fraud_reason"
    ]].to_string()
)


# ==================================================
# 10. SAVE FRAUD ANALYSIS DATASET
# ==================================================
# The enriched dataset contains:
#
# final_category
# pseudo_fraud_label
# risk_score
# is_fraud
# fraud_reason
#
# This dataset can be used by dashboards,
# APIs, or downstream analytics pipelines.

df.to_csv(
    "../data/processed/transactions_with_fraud.csv",
    index=False
)

print("\nFraud analysis dataset saved to:")
print("data/processed/transactions_with_fraud.csv")


# ==================================================
# SAVE TRAINED MODEL
# ==================================================

# save random forest model
with open("trained/fraud_model.pkl", "wb") as f:
    pickle.dump(rf_model, f)

# save encoders used during training
with open("trained/category_encoder.pkl", "wb") as f:
    pickle.dump(category_encoder, f)

with open("trained/location_encoder.pkl", "wb") as f:
    pickle.dump(location_encoder, f)

with open("trained/device_encoder.pkl", "wb") as f:
    pickle.dump(device_encoder, f)

print("Encoders saved successfully.")